kind: pipeline
name: default

steps:
- name: submodule-init
  image: alpine/git:latest
  pull: if-not-exists
  commands:
    - git submodule init
    - git submodule update

- name: build
  image: plugins/hugo
  pull: if-not-exists
  settings:
    hugo_version: 0.101.0
    extended: true
    url: https://blog.azurcrystal.com
  

- name: deploy
  image: appleboy/drone-scp
  pull: if-not-exists
  settings:
    host:
      from_secret: HOST
    username:
      from_secret: SSH_USERNAME
    key:
      from_secret: SSH_KEY
    target: 
      from_secret: DEPLOY_PATH
    source: public/*

trigger:
  branch:
    - next
  event:
    - push

---
kind: secret
name: HOST
get:
    path: drone-ci/data/blog.azurcrystal.com
    name: host

---
kind: secret
name: SSH_USERNAME
get:
    path: drone-ci/data/blog.azurcrystal.com
    name: ssh_username

---
kind: secret
name: SSH_KEY
get:
    path: drone-ci/data/blog.azurcrystal.com
    name: ssh_key

---
kind: secret
name: DEPLOY_PATH
get:
    path: drone-ci/data/blog.azurcrystal.com
    name: deploy_path